"""System policies."""

from .const import (
    CAT_AUTOMATIONS,
    CAT_ENTITIES,
    CAT_SERVICES,
    POLICY_CONTROL,
    POLICY_READ,
    POLICY_TRIGGER,
    SUBCAT_ALL,
)

ADMIN_POLICY = {
    CAT_ENTITIES: True,
    CAT_SERVICES: True,
    CAT_AUTOMATIONS: True,
}

USER_POLICY = {
    CAT_ENTITIES: True,
    CAT_SERVICES: True,
    CAT_AUTOMATIONS: {
        SUBCAT_ALL: {POLICY_READ: True, POLICY_TRIGGER: True},
    },
}

READ_ONLY_POLICY = {
    CAT_ENTITIES: {SUBCAT_ALL: {POLICY_READ: True}},
    CAT_SERVICES: {SUBCAT_ALL: {POLICY_READ: True}},
    CAT_AUTOMATIONS: {SUBCAT_ALL: {POLICY_READ: True}},
}
